### ISSUE TITLE
dataLocaleData is used before its definition in InitializeDateTimeFormat()

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-intl-datetime-style#25]
> 7. Let hcDefault be dataLocaleData.[[hourCycle]].
>
> ...
>
> 26. Let dataLocaleData be localeData.[[&lt;dataLocale>]].

**Comment by littledan** [comment]
The numbering I see differs a bit, but it looks like the definition of `localeData` could simply be hoisted above its use, right? Would you be available to make a PR for this, @Ms2ger ?
