### ISSUE TITLE
Missing "," in or-list in DateTimeStylePattern

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-datetime-style#36]
Missing Oxford comma in steps 1.a and 2.a in `"medium" or "short"`.

**Comment by anba** [comment]
And in https://tc39.es/proposal-intl-datetime-style/#sec-properties-of-intl-datetimeformat-instances

**Comment by anba** [comment]
And in the preamble of DateTimeStylePattern.

**Comment by littledan** [comment]
Thanks for cataloguing these errors. @Ms2ger , could you prepare a fix?
